name: Create a GitHub mirror of the VDR sources and update the GitHub wiki
on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: '20 1 * * *'
  workflow_dispatch:

jobs:
  automirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install mandoc
        run: |
          sudo apt-get install mandoc
      - name: Setup git identity
        run: |
          git config --global user.email "automirror@nohost.invalid"
          git config --global user.name "AutoMirror Bot"
      - name: Setup SSH Keys and known hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
      - name: Run automirror
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          make

