name: Create a GitHub mirror of the VDR sources and update the GitHub wiki
on:
  - push
jobs:
  automirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install pandoc
        run: |
          sudo apt-get install pandoc
      - name: Setup SSH Keys and known hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
      - name: Run automirror
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          make

